In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm.notebook import tqdm
import datamol as dm

In [3]:
df = pd.read_csv("../data/Vapor_pressures.csv")
df.head()

,Name,CAS-RN,Formula,SMILES,T,Pvap,KDB_ID,Class,Subclass
0,METHANE,74-82-8,CH4,C,90.670000,11.702099,1,Paraffinic Hydrocarbons,n-Alkanes
1,METHANE,74-82-8,CH4,C,94.115172,17.886999,1,Paraffinic Hydrocarbons,n-Alkanes
2,METHANE,74-82-8,CH4,C,97.560345,26.489535,1,Paraffinic Hydrocarbons,n-Alkanes
3,METHANE,74-82-8,CH4,C,101.005517,38.137051,1,Paraffinic Hydrocarbons,n-Alkanes
4,METHANE,74-82-8,CH4,C,104.450690,53.534190,1,Paraffinic Hydrocarbons,n-Alkanes

In [5]:
def get_fp(mol, fp_type='topological'):
    return dm.to_fp(mol, fp_type=fp_type)

df['Mol'] = df['SMILES'].apply(dm.to_mol)
df['Fingerprint'] = df['Mol'].apply(get_fp)
df.head()

,Name,CAS-RN,Formula,SMILES,T,Pvap,KDB_ID,Class,Subclass,Mol,Fingerprint
0,METHANE,74-82-8,CH4,C,90.670000,11.702099,1,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB80...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,METHANE,74-82-8,CH4,C,94.115172,17.886999,1,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB80...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,METHANE,74-82-8,CH4,C,97.560345,26.489535,1,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB80...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,METHANE,74-82-8,CH4,C,101.005517,38.137051,1,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB80...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,METHANE,74-82-8,CH4,C,104.450690,53.534190,1,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB80...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."

In [8]:
df["ln_P"] = np.log(df.Pvap)

In [9]:
df.columns.tolist()

['Name',
 'CAS-RN',
 'Formula',
 'SMILES',
 'T',
 'Pvap',
 'KDB_ID',
 'Class',
 'Subclass',
 'Mol',
 'Fingerprint',
 'ln_P']

In [13]:
# Splitting the dataset in such a way that the training data/compounds should not be in test data/compounds

from sklearn.model_selection import train_test_split
chemical_classes = df["Class"].unique()
# 3 different dataset for storing the names of the compounds
train_comps, valid_comps, test_comps = [], [], []
for cl in chemical_classes:
    # take all the data belonging to cl class
    df_cl = df[df["Class"]==cl]
    # Get unique compound for this data belonging to cl class
    unique_compound_cl = df_cl["Name"].unique().tolist()
    # Split into train and test
    train_all, comp_test = train_test_split(unique_compound_cl, test_size = 0.20, random_state = 0)
    # Split the train all to train and valid 
    comp_train, comp_valid = train_test_split(train_all, test_size = 0.20, random_state = 1)

    train_comps.extend(list(comp_train))
    valid_comps.extend(list(comp_valid))
    test_comps.extend(list(comp_test))

In [14]:
print(train_comps)

['4-METHYLHEPTANE', 'ISOBUTANE', '3,3-DIMETHYLHEPTANE', '2,2-DIMETHYLOCTANE', '3-METHYLHEXANE', 'N-HEXADECANE', 'N-BUTANE', '3,4-DIMETHYLHEPTANE', '3-METHYLNONANE', '3,3,4-TRIMETHYLHEPTANE', '4-METHYLNONANE', 'N-HEXATRIACONTANE', 'N-DODECANE', '2,2,6-TRIMETHYLHEPTANE', '3-METHYL-3-ETHYLPENTANE', '2,4-DIMETHYL-3-ETHYLHEXANE', '2,4-DIMETHYLHEPTANE', '3-ETHYLHEXANE', '4-ETHYLOCTANE', '2,4,5-TRIMETHYLHEPTANE', '2,4-DIMETHYL-3-ISOPROPYLPENTANE', '2,3,3-TRIMETHYLHEPTANE', '2,3,4,4-TETRAMETHYLHEXANE', '2-METHYL-4-ETHYLHEPTANE', '2,3,3,5-TETRAMETHYLHEXANE', '3,3,5-TRIMETHYLHEPTANE', '2,5-DIMETHYLHEXANE', '2,2,4-TRIMETHYLHEXANE', 'N-PENTADECANE', '2,3,6-TRIMETHYLHEPTANE', 'N-EICOSANE', '2,2,4-TRIMETHYLPENTANE', '2,2,3,3-TETRAMETHYLBUTANE', '2-METHYLHEXANE', 'N-UNDECANE', 'N-TRICOSANE', 'N-TRITRIACONTANE', '3-METHYLHEPTANE', '2,3,4-TRIMETHYLHEPTANE', '2,3,5-TRIMETHYLHEXANE', '2,2,3,4,4-PENTAMETHYLPENTANE', '3,3-DIMETHYL-4-ETHYLHEXANE', '4,5-DIMETHYLOCTANE', 'N-TRIDECANE', '2,3-DIMETHYL-4-ETHYLHEXANE', '3,3,4,4-TETRAMETHYLHEXANE', 'N-DECANE', '2,2,3-TRIMETHYLPENTANE', '2,4-DIMETHYLHEXANE', '3-ETHYL-2,3,4-TRIMETHYLPENTANE', '3,3-DIETHYL-2-METHYLPENTANE', '4-METHYL-4-ETHYLHEPTANE', '2,2,3,5-TETRAMETHYLHEXANE', '2,3-DIMETHYL-3-ETHYLHEXANE', '5-METHYLNONANE', '3,5-DIMETHYLOCTANE', '2,6-DIMETHYLHEPTANE', '3-METHYL-3-ETHYLHEPTANE', 'N-DOTRIACONTANE', '2,2,4,5-TETRAMETHYLHEXANE', '3-ETHYL-4-METHYLHEXANE', '2,2-DIMETHYLHEPTANE', '2,2,3,3-TETRAMETHYLHEXANE', 'N-DOCOSANE', '2,5-DIMETHYL-3-ETHYLHEXANE', '2-METHYL-3-ETHYLHEPTANE', '2,2-DIMETHYLHEXANE', '3,4-DIETHYLHEXANE', '4-METHYLOCTANE', '2,3-DIMETHYLHEXANE', '2-METHYLHEPTANE', '2,2,4-TRIMETHYLHEPTANE', '2-METHYL-5-ETHYLHEPTANE', '2,4-DIMETHYL-3-ETHYLPENTANE', 'N-TETRADECANE', '4-METHYL-3-ETHYLHEPTANE', 'N-HENEICOSANE', '4-ETHYL-2-METHYLHEXANE', '4,4-DIMETHYLOCTANE', '3,4-DIMETHYLOCTANE', '4-PROPYLHEPTANE', '3,4,4-TRIMETHYLHEPTANE', '2,2-DIMETHYLPENTANE', 'N-OCTADECANE', '2,4-DIMETHYLOCTANE', '3-ETHYL-3-METHYLHEXANE', '2,2-DIMETHYL-3-ETHYLHEXANE', '3-ETHYL-2,2,3-TRIMETHYLPENTANE', '3-ETHYL-2,2,4-TRIMETHYLPENTANE', '2,3-DIMETHYLOCTANE', '3-METHYLOCTANE', 'N-HEPTADECANE', '3-METHYL-5-ETHYLHEPTANE', '2,2,4,4-TETRAMETHYLPENTANE', '2,2,5-TRIMETHYLHEPTANE', '2,3,5-TRIMETHYLHEPTANE', '3-METHYLPENTANE', '2,5-DIMETHYLHEPTANE', '2-METHYLPENTANE', '3,3,4-TRIMETHYLHEXANE', '3,4-DIMETHYL-3-ETHYLHEXANE', 'N-OCTACOSANE', '3,5-DIMETHYLHEPTANE', '2,2-DIMETHYLBUTANE', '2,3-DIMETHYL-3-ETHYLPENTANE', '4-ETHYLHEPTANE', '2,3,3-TRIMETHYLHEXANE', '2,4-DIMETHYLPENTANE', '1-HEXYNE', '1-HEPTENE', '3,3-DIMETHYL-1-BUTENE', '1-HEXADECYNE', '2,4-DIMETHYL-2-PENTENE', 'CIS-3-OCTENE', 'CIS-3-HEXENE', 'TRANS-2-HEPTENE', '1,5-HEXADIENE', '1-DODECYNE', 'TRANS-2-HEXENE', '2-ETHYL-1-PENTENE', 'TRANS-4-OCTENE', 'CIS-3-HEPTENE', '2,4,4-TRIMETHYL-2-PENTENE', '2-METHYL-1-PENTENE', 'CIS,TRANS-2,4-HEXADIENE', '2-METHYL-2-PENTENE', '2-METHYL-1-BUTENE', '2-HEPTYNE', '3-HEXYNE', '1-PENTADECYNE', '3-METHYL-1,2-BUTADIENE', '1-PENTYNE', '3-METHYL-2-ETHYL-1-BUTENE', '2-METHYL-1-HEXENE', '1,3-BUTADIENE', '1-TETRADECENE', '1-TETRADECYNE', '1,2-PENTADIENE', '2-PENTYNE', '1-HEXADECENE', '2,3-DIMETHYL-1-BUTENE', '2-ETHYL-1-BUTENE', '2,4-DIMETHYL-1-PENTENE', '3-HEPTYNE', 'ETHYLENE', '4-METHYL-CIS-2-PENTENE', '2,5-DIMETHYL-2,4-HEXADIENE', '1-HEPTADECYNE', '1-HEPTADECENE', '2,4,4-TRIMETHYL-1-PENTENE', '2,3-DIMETHYL-1,3-BUTADIENE', '2,3-PENTADIENE', 'CIS-2-HEXENE', '3-METHYL-CIS-2-PENTENE', '4-METHYL-1-PENTENE', '2-METHYL-2-BUTENE', '1-OCTADECYNE', 'CIS-1,3-PENTADIENE', '2-OCTYNE', '1-DECENE', '3-METHYL-1-BUTYNE', '1-OCTADECENE', '1-OCTYNE', '2,5-DIMETHYL-1,5-HEXADIENE', '1-NONADECENE', 'PROPYLENE', '1-PENTENE', '1-DODECENE', '3-METHYL-1-PENTENE', '2-ETHYL-1-HEXENE', '2-METHYL-2-HEPTENE', '1-HEPTYNE', '2-METHYL-2-HEXENE', '3-METHYL-TRANS-3-HEXENE', 'CIS-4-OCTENE', 'ISOPRENE', '1-PENTADECENE', '2,2-DIMETHYL-CIS-3-HEXENE', 'TRANS-2-OCTENE', '3-OCTYNE', 'CIS-2-BUTENE', '1,4-PENTADIENE', 'PROPADIENE', '3-METHYL-CIS-3-HEXENE', '4-METHYLCYCLOHEXENE', 'N-PENTYLCYCLOPENTANE', 'ISOPROPYLCYCLOPENTANE', '4-METHYLCYCLOPENTENE', 'CIS,TRANS-1,3,5-TRIMETHYLCYCLOHEXANE', 'CIS,TRANS-1,2,4-TRIMETHYLCYCLOPENTANE', '1-METHYLCYCLOHEXENE', '1,1,3-TRIMETHYLCYCLOPENTANE', '1,1,2-TRIMETHYLCYCLOPENTANE', 'CYCLOBUTANE', 'CYCLOOCTANE', 'ISOBUTYLCYCLOHEXANE', 'N-OCTYLCYCLOPENTANE', 'CYCLOPROPANE', 'N-HEXYLCYCLOHEXANE', '3-METHYLCYCLOPENTENE', 'CYCLOHEPTANE', '1-METHYL-1-ETHYLCYCLOPENTANE', 'CYCLOPENTENE', '4-VINYLCYCLOHEXENE', 'ETHYLCYCLOPENTANE', 'ISOPROPYLCYCLOHEXANE', 'N-DODECYLCYCLOPENTANE', 'METHYLCYCLOHEXANE', 'CIS,CIS-1,3,5-TRIMETHYLCYCLOHEXANE', 'CYCLOBUTENE', 'CIS-1,3-DIMETHYLCYCLOPENTANE', 'TRANS-1,2-DIMETHYLCYCLOHEXANE', 'TRANS-1,3-DIMETHYLCYCLOPENTANE', 'BICYCLOHEXYL', '1-METHYLCYCLOPENTENE', 'TERT-BUTYLCYCLOHEXANE', 'N-NONYLCYCLOPENTANE', '3-ETHYLCYCLOPENTENE', 'CYCLOHEXENE', 'CIS-1,4-DIMETHYLCYCLOHEXANE', 'METHYLCYCLOPENTANE', 'CYCLOHEPTENE', 'N-BUTYLCYCLOPENTANE', '1,1-DIMETHYLCYCLOPENTANE', 'CYCLOPENTANE', 'N-DODECYLCYCLOHEXANE', 'CYCLOHEXANE', 'DICYCLOPENTADIENE', 'N-HEPTYLCYCLOPENTANE', 'TRANS-1,2-DIMETHYLCYCLOPENTANE', 'P-XYLENE', 'P-DIISOPROPYLBENZENE', '2-ETHYL-6-METHYLNAPHTHALENE', 'P-TERPHENYL', 'TRIPHENYLETHYLENE', 'PENTAMETHYLBENZENE', 'TERT-BUTYLBENZENE', 'N-NONYLBENZENE', 'INDENE', '2,3-DIMETHYL-2,3-DIPHENYLBUTANE', 'PYRENE', 'N-BUTYLBENZENE', '1,2,4-TRIETHYLBENZENE', '1,2,3,5-TETRAMETHYLBENZENE', '2-ETHYL-P-XYLENE', '1,2,3-TRIMETHYLBENZENE', 'ISOBUTYLBENZENE', 'FLUORENE', 'P-CYMENE', 'NAPHTHALENE', '2-ETHYL-3-METHYLNAPHTHALENE', 'N-TRIDECYLBENZENE', 'NAPHTHACENE', '1,6-DIMETHYLNAPHTHALENE', 'BIPHENYL', 'N-HEPTYLBENZENE', 'BENZENE', '1,2,3,4-TETRAHYDRONAPHTHALENE', 'P-DIETHYLBENZENE', '1-PENTYLNAPHTHALENE', '5-ETHYL-M-XYLENE', '1-METHYL-2-PROPYLBENZENE', '1-METHYLINDENE', '1-METHYLNAPHTHALENE', '1,2,3-TRIMETHYLINDENE', '2-METHYLNAPHTHALENE', '1-N-NONYLNAPHTHALENE', 'INDANE', '1,2,4,5-TETRAMETHYLBENZENE', 'N-DODECYLBENZENE', '1,4-DIMETHYLNAPHTHALENE', 'P-METHYLSTYRENE', '1,2,3-TRIETHYLBENZENE', '1,2,3,5-TETRAETHYLBENZENE', '1,2,3,4-TETRAETHYLBENZENE', 'TRIPHENYLENE', 'O-CYMENE', 'CHRYSENE', '1,1-DIPHENYLETHANE', '1,5-DIMETHYLNAPHTHALENE', '1-N-DECYLNAPHTHALENE', 'STYRENE', '1-ETHYL-3-ETHENYLBENZENE', '2-PENTYLNAPHTHALENE', 'O-TERPHENYL', '1-PHENYLNAPHTHALENE', 'N-OCTYLBENZENE', 'TOLUENE', '1-PENTAETHYLBENZENE', '2,6-DIMETHYLNAPHTHALENE', 'CIS-STILBENE', '3-ETHYL-O-XYLENE', 'DIPHENYLMETHANE', '2-ETHYL-7-METHYLNAPHTHALENE', 'M-METHYLSTYRENE', 'M-DIETHYLBENZENE', 'BENZANTHRACENE', '1,3,5-TRIMETHYLBENZENE', 'FLUORANTHENE', '1,2-DIMETHYLNAPHTHALENE', '1-ETHYL-4-ETHENYLBENZENE', 'HEXAETHYLBENZENE', 'HEXAMETHYLBENZENE', '1,2,4,5-TETRAETHYLBENZENE', '3,5-DIETHYLTOLUENE', 'N-PROPYLBENZENE', 'O-DIISOPROPYLBENZENE', '1-METHYLCYCLOHEXANOL', '2-METHYL-1-BUTANOL', '2-NONANOL', '1,2-PROPYLENE GLYCOL', '2-METHYL-1-PENTANOL', '2-PHENYLETHANOL', '2-ETHYL-1-BUTANOL', 'ETHANOL', '1-HEXADECANOL', '1-HEPTANOL', '3-METHYL-1-BUTANOL', '1-EICOSANOL', 'P-CRESOL', 'P-TERT-AMYLPHENOL', 'CYCLOHEPTANOL', 'P-TERT-BUTYLPHENOL', '2-OCTANOL', '1,2,3-BENZENETRIOL', '1,2-BENZENEDIOL', '2,6-DI-TERT-BUTYL-P-CRESOL', 'O-CRESOL', '3-METHYL-2-BUTANOL', 'TRIETHYLENE GLYCOL', '3,5-XYLENOL', '2,6-DIMETHYL-4-HEPTANOL', '2,2-DIMETHYL-1-PROPANOL', 'CIS-2-METHYLCYCLOHEXANOL', 'FURFURYL ALCOHOL', 'THYMOL', 'MENTHOL', 'O-ETHYLPHENOL', 'TRANS-3-METHYLCYCLOHEXANOL', 'P-CUMYLPHENOL', 'NEOPENTYL GLYCOL', 'P-ETHYLPHENOL', 'PHENOL', '1-TRIDECANOL', '2,4,6-TRIMETHYL PHENOL', 'NONYLPHENOL', 'DINONYLPHENOL', '1,6-HEXANEDIOL', 'CYCLOHEXANOL', 'N-BUTANOL', 'BENZYL ALCOHOL', 'TRANS-2-BUTENE-1,4-DIOL', '1-NONANOL', '2,3-BUTANEDIOL', 'ISOBUTANOL', 'CIS-2-BUTENE-1,4-DIOL', 'CYCLOPENTANOL', 'CARVACROL', '4-METHYL-2-PENTANOL', '2-HEXANOL', 'TETRAETHYLENE GLYCOL', 'GLYCEROL', 'ISOPROPANOL', '3,4-XYLENOL', '1-OCTADECANOL', 'SEC-BUTANOL', '2-PENTANOL', 'DIMETHYL PHENYL CARBINOL', '1-PENTADECANOL', 'TETRAHYDROFURFURYL ALCOHOL', 'ISOHEPTANOL', 'N-MARGARIC ACID', 'ISO-CAPROIC ACID', 'N-STEARIC ACID', 'METHACRYLIC ACID', 'N-PALMITIC ACID', 'ISOVALERIC ACID', 'TEREPHTHALIC ACID', 'N-BUTYRIC ACID', 'ACRYLIC ACID', 'O-METHOXYBENZOIC ACID', 'N-LAURIC ACID', 'GLUTARIC ANHYDRIDE', 'PROPIONIC ANHYDRIDE', 'ACETIC ACID', 'TARTARIC ACID', 'SALICYLIC ACID', 'BUTYRIC ANHYDRIDE', 'MALEIC ANHYDRIDE', 'TRANS-CROTONIC ACID', 'N-CAPROIC ACID', 'N-PELARGONIC ACID', 'PHTHALIC ACID', 'N-UNDECYLIC ACID', 'SUCCINIC ANHYDRIDE', 'FUMARIC ACID', 'MALEIC ACID', 'N-OENANTHIC ACID', 'N-VALERIC ACID', 'SUBERIC ACID', 'N-PENTADECYLIC ACID', 'ISOPHTHALIC ACID', 'MALONIC ACID', 'PHTHALIC ANHYDRIDE', 'LACTIC ACID', 'DI-N-OCTYL ETHER', '2-METHYLBENZOFURAN', 'ISOPROPYL-TERT-BUTYL ETHER', 'METHYL N-BUTYL ETHER', 'TETRAHYDROPYRAN', 'DIVINYL ETHER', 'METHYL ISOBUTYL ETHER', 'METHYL ISOPROPYL ETHER', 'ETHYLENE GLYCOL DIETHYL ETHER', 'TRIOXANE', 'N-BUTYL ETHYL ETHER', '1,1-DIMETHOXYETHANE', 'DI-N-BUTYL ACETAL', 'METHYL VINYL ETHER', 'ETHYLENE OXIDE', 'METHYL PROPYL ETHER', 'BUTYL VINYL ETHER', 'ETHYL PROPYL ETHER', 'METHYL TERT-PENTYL ETHER', 'DI-N-PROPYL ETHER', 'METHYLAL', '1,2-DIMETHOXYETHANE', 'DIHYDROPYRAN', '1,2-EPOXYBUTANE', 'TETRAHYDROFURAN', 'DI-SEC-BUTYL ETHER', 'DIETHYL ETHER', 'DIBENZYL ETHER', 'DIPHENYL ETHER', 'ACETAL', '2,5-DIHYDROFURAN', 'DIMETHYL ETHER', 'N-OCTYL FORMATE', 'DIETHYL PHTHALATE', 'ISOPROPYL ACETATE', 'ISOPENTYL FORMATE', 'N-PROPYL N-BUTYRATE', 'DIETHYL OXALATE', 'N-BUTYL FORMATE', 'ISOBUTYL ACRYLATE', 'METHYL ACETATE', 'METHYL ACRYLATE', 'ETHYL BENZOATE', 'METHYL FUMARATE', 'ETHYL SUCCINATE', 'ETHYL GLUTARATE', 'N-BUTYL NONANOATE', 'ISOPROPENYL ACETATE', 'N-DECYL ACETATE', 'N-PENTYL ACETATE', 'N-PENTYL PROPIONATE', 'ISOBUTYL N-BUTYRATE', 'VINYL PROPIONATE', 'ISOAMYL PROPIONATE', 'ETHYL METHACRYLATE', 'DIMETHYL TEREPHTHALATE', 'VINYL FORMATE', 'ISOBUTYL VALERATE', 'DIMETHYL MALEATE', 'DI(2-ETHYLHEXYL) PHTHALATE', 'METHYL SALICYLATE', 'METHYL BENZOATE', 'ISOBUTYL PROPIONATE', 'DIALLYL MALEATE', 'VINYL ACETATE', 'DIMETHYL PHTHALATE', 'BENZYL BENZOATE', 'N-HEPTYL ACETATE', 'N-BUTYL N-BUTYRATE', 'ISO-PROPYL ISO-BUTYRATE', 'METHYL DODECANOATE', 'ETHYL N-BUTYRATE', 'METHYL VALERATE', 'ETHYL PHENYLACETATE', 'SEC-BUTYL ACETATE', 'METHYL PROPIONATE', 'N-BUTYL VALERATE', '2-HYDROXYETHYL ACRYLATE', 'N-PENTYL FORMATE', 'ETHYLIDENE DIACETATE', 'ETHYL ACETATE', 'N-PROPYL ACRYLATE', 'DIBUTYL PHTHALATE', 'N-BUTYL STEARATE', 'DIETHYL MALONATE', 'ETHYLENE GLYCOL DIACETATE', 'METHYL OLEATE', 'DIMETHYL OXALATE', '2-ETHYLHEXYL ACETATE', 'BENZYL ACETATE', 'N-PROPYL FORMATE', 'N-BUTYL METHACRYLATE', 'ETHYL STEARATE', 'ETHYL ISOBUTYRATE', 'DIMETHYL ISOPHTHALATE', 'N-BUTYL ACETATE', 'METHYL-N-HEPTYL KETONE', 'DIETHYL KETONE', 'DIISOBUTYL KETONE', 'CAMPHOR', 'CYCLOBUTANONE', 'METHYL SEC-BUTYL KETONE', 'DIKETENE', 'BENZOPHENONE', 'CYCLOHEXANONE', 'MESITYL OXIDE', 'CYCLOOCTANONE', 'ETHYL N-PROPYL KETONE', 'ETHYL ISOPROPYL KETONE', 'ACETYLACETONE', 'METHYL ETHYL KETONE', 'ACETONE', 'METHYL N-PROPYL KETONE', 'METHYL AMYL KETONE', 'METHYL ISOBUTYL KETONE', 'ETHYL BUTYL KETONE', '5-METHYL-2-HEXANONE', 'CYCLOHEPTANONE', 'N-BUTYRALDEHYDE', 'ISOBUTYRALDEHYDE', 'FORMALDEHYDE', '1-OCTANAL', '1-TRIDECANAL', 'VANILLIN', 'ACETALDEHYDE', '1-DODECANAL', 'SALICYLALDEHYDE', 'VALERALDEHYDE', 'N-PROPIONALDEHYDE', '1-HEPTANAL', '1-NONANAL', '1-HEXANAL', 'DIETHANOLAMINE', '2,6-DIETHYLANILINE', 'N-OCTYLAMINE', '2-METHYL-5-ETHYLPYRIDINE', 'TRIMETHYLAMINE', 'DIMETHYL-O-TOLUIDINE', 'TRIETHYLAMINE', 'M-CHLOROANILINE', 'ETHYLENEIMINE', '4-METHYLQUINOLINE', '2,4-DIMETHYLPYRIDINE', 'M-PHENYLENEDIAMINE', 'M-NITROANILINE', 'PYRROLE', 'MONOETHANOLAMINE', 'BENZYLAMINE', '6-METHYLQUINOLINE', 'N-DECYLAMINE', '2,6-DIMETHYLQUINOLINE', '4-ETHYLPYRIDINE', '8-METHYLQUINOLINE', 'N-NONYLAMINE', 'ETHYLAMINE', 'N-ETHYLANILINE', 'N-BUTYLANILINE', 'CYCLOHEXYLAMINE', 'ISOBUTYLAMINE', '2-METHYLPYRIDINE', 'N-METHYL DIPHENYLAMINE', 'SEC-BUTYLAMINE', '2,6-DIMETHYLPYRIDINE', 'HEXAMETHYLENEDIAMINE', 'ISOPROPYLAMINE', '2-PYRROLIDONE', 'TRI-N-AMYLAMINE', 'TETRAETHYLENEPENTAMINE', 'P-CHLOROANILINE', 'O-PHENYLENEDIAMINE', 'DICYCLOHEXYLAMINE', 'N-PROPYLAMINE', 'ALLYLAMINE', 'TRIETHANOLAMINE', 'ANILINE', 'N,N-DIMETHYLANILINE', 'HEXAMETHYLENETETRAMINE', 'HEXAMETHYLENEIMINE', 'PYRAZINE', 'TOLUENEDIAMINE', 'TRIETHYLENEDIAMINE', '3-ETHYLPYRIDINE', 'N-DODECYLAMINE', 'N-PENTYLAMINE', '3,4-DIMETHYLPYRIDINE', 'O-TOLUIDINE', 'M-TOLUIDINE', '2-NAPHTHYLAMINE', 'N-TETRADECYLAMINE', 'DIETHYLAMINE', '2,5-DIMETHYLPYRIDINE', '2,4-DIMETHYLANILINE', 'O-NITROANILINE', '3,5-DIMETHYLPYRIDINE', 'DIPHENYLAMINE', '2,3-DIMETHYLPYRIDINE', '4-METHYLPYRIDINE', 'DIISOBUTYLAMINE', 'PIPERIDINE', '2-METHYLPIPERIDINE', 'DIETHYLENE TRIAMINE', 'P-ETHYLANILINE', 'O-ETHYLANILINE', 'DIBENZOPYRROLE', '1-NAPHTHYLAMINE', 'ACETANILIDE', 'FORMAMIDE', 'TERT-BUTYLFORMAMIDE', '2-METHACRYLAMIDE', 'ACRYLAMIDE', 'N,N-DIMETHYLFORMAMIDE', 'VINYLACETONITRILE', 'ADIPONITRILE', 'TRANS-CROTONITRILE', 'ETHYLENE DICYANIDE', 'PENTAMETHYLENE DICYANIDE', 'ACRYLONITRILE', 'N-CAPRINITRILE', 'TRIMETHYLENE DICYANIDE', 'PHENYL ACETONITRILE', 'CIS-CROTONITRILE', 'BENZONITRILE', 'ISOBUTYRONITRILE', 'METHYLGLUTARONITRILE', 'O-TOLUNITRILE', 'N-VALERONITRILE', 'PROPIONITRILE', 'L-PROLINE', '1-AMINOHEPTANE', '3,5-DINITROTOLUENE', 'O-NITROPHENOL', 'HYDRAZOBENZENE', '1-NITROPROPANE', 'PHENYL ISOCYANATE', '2-NITROBUTANE', 'NITROMETHANE', 'PICRIC ACID', 'LYSINE', 'NITROGLYCERINE', '2,4,6-TRINITROTOLUENE', 'ETHYLENE GLYCOL DINITRATE', 'PHENYLHYDRAZINE', 'METHYL NITRATE', 'NICOTINE', '1-NITROBUTANE', '2,5-DINITROTOLUENE', 'PARA-AZOXYANISOLE', '2,4-DINITROPHENOL', 'M-DINITROBENZENE', 'NITROBENZENE', '2-ETHYL-1-NITROBENZENE', 'P-PHENETIDINE', '3,4-DINITROTOLUENE', 'P-NITROPHENOL', 'METHYL HYDRAZINE', 'METHYL ISOCYANATE', '2-NITROPROPANE', '1,3-DIPHENYLTRIAZENE', 'N,N-DIMETHYL-P-TOLUIDINE', 'ETHYL CYANOACETATE', 'MORPHOLINE', 'EPSILON-CAPROLACTAM', 'CHLOROACETYL CHLORIDE', '1-FLUOROPROPANE', 'FLUOROMETHANE', '3,4-DICHLOROPHENYL ISOCYANATE', '1,1,2,2-TETRABROMOETHANE', '1,1,2-TRICHLOROETHANE', '1-BROMOBUTANE', 'BROMOPENTAFLUOROBENZENE', 'P-DIFLUOROBENZENE', '1,1,1,2-TETRACHLORODIFLUOROETHANE', 'CHLORODIFLUOROMETHANE', 'O-CHLOROTOLUENE', '1,2-DIIODOPROPANE', 'MONOFLUOROACETIC ACID', 'CHLOROPENTAFLUOROETHANE', '1-CHLORO-2,2-DIFLUOROETHYLENE', '1,2-DIBROMOETHANE', '1-CHLOROPENTANE', 'O-FLUOROTOLUENE', 'BROMOTRIFLUOROMETHANE', '1-CHLORONAPHTHALENE', 'CIS-1,2-DICHLOROETHYLENE', 'HEXAFLUOROETHANE', '1-BROMOHEPTANE', 'CARBONYL FLUORIDE', '2,3-DICHLOROPROPENE', '2-CHLOROBUTANE', 'OCTAFLUORO-2-BUTENE', '1,2-DIIODOETHANE', '1,3-DICHLOROPROPANE', 'ACETYL CHLORIDE', '1,4-DICHLOROBUTANE', '1-FLUOROPENTANE', 'METHYL CHLOROFORMATE', 'OCTAFLUOROCYCLOBUTANE', 'DICHLORODIFLUOROMETHANE', 'PERFLUORO-2-METHYLPENTANE', '1,3,5-TRICHLOROTRIFLUOROBENZENE', 'HEXAFLUOROPROPYLENE', 'PENTAFLUOROPHENOL', '2-IODOPROPANE', 'CHLOROBENZENE', 'CHLOROETHANE', '1,1-DICHLOROETHYLENE', '1-CHLOROBUTANE', 'PERFLUORO-3-METHYLPENTANE', '1,1,1-TRICHLOROETHANE', 'ISO-AMYL BROMIDE', '1-BROMONONANE', 'O-DIFLUOROBENZENE', 'IODOMETHANE', 'TRIBROMOMETHANE', 'FLUOROETHANE', 'VINYL BROMIDE', '1,2-DIBROMOCYCLOHEXANE', 'BROMOETHANE', 'PENTACHLOROPHENOL', '4-CHLORO-3-NITROBENZOTRIFLUORIDE', '1-CHLOROPROPANE', '2,3-DICHLORO-1,3-BUTADIENE', 'M-DIBROMOBENZENE', 'DICHLOROACETIC ACID', '1-BROMOPROPANE', '1,3,5-TRIFLUOROBENZENE', 'PENTAFLUOROETHANE', 'M-CHLOROTOLUENE', '1-BROMOPENTANE', '1,2-DIFLUOROETHANE', '1,1,1-TRIFLUOROETHANE', '1,1-DIFLUORO-1,2-DICHLOROETHANE', '2-CHLOROPROPENE', '1-CHLORO-1,1-DIFLUOROETHANE', '1,1-DICHLOROTETRAFLUOROETHANE', 'DIIODOMETHANE', 'BROMOCHLORODIFLUOROMETHANE', '1,3-DIBROMOPROPANE', 'CIS-1,2-DIIODOETHYLENE', 'DIBROMOMETHANE', '1,1,1,2,2-PENTAFLUOROPROPANE', '1,2-DICHLOROTETRAFLUOROETHANE', 'O-DIBROMOBENZENE', 'O-DICHLOROBENZENE', 'PENTAFLUOROBENZENE', '1,5-DICHLOROPENTANE', 'P-FLUOROTOLUENE', 'TETRACHLOROETHYLENE', 'DICHLOROACETALDEHYDE', '1,2,3,5-TETRAFLUOROBENZENE', '1,2,4,5-TETRAFLUOROBENZENE', '1,1-DIBROMOETHANE', 'CYCLOPENTYL CHLORIDE', 'M-FLUOROTOLUENE', 'O-CHLORONITROBENZENE', '1,1-DICHLOROPROPANE', '3-IODO-1-PROPENE', '1,1-DIFLUOROETHYLENE', '2-BROMO-2-CHLORO-1,1,1-TRIFLUOROETHANE', '3,4-DICHLOROANILINE', '1-FLUOROHEXANE', 'TRIFLUOROETHYLENE', '1,2-DIBROMOBUTANE', '1,4-DICHLORO-CIS-2-BUTENE', '1-FLUOROHEPTANE', '1,3-DICHLORO-TRANS-2-BUTENE', '2-CHLOROPROPANE', '1,3,5-TRICHLOROBENZENE', '1,1-DICHLOROETHANE', '1,2-DIBROMOPROPANE', 'PERFLUOROPENTANE', 'FLUOROBENZENE', 'BENZOYL CHLORIDE', 'CHLOROPRENE', 'P-CHLOROTOLUENE', 'TRICHLOROACETYLCHLORIDE', 'CHLOROFORM', '1-BROMODODECANE', '1-BROMODECANE', 'DECAFLUOROBUTANE', 'P-BROMOTOLUENE', 'DIFLUOROMETHANE', '1,1-DICHLORO-2,2,2-TRIFLUOROETHANE', 'VINYL FLUORIDE', '1,2-DIBROMOTETRAFLUOROETHANE', 'M-BROMOTOLUENE', '2,4-DICHLOROTOLUENE', 'BENZYL CHLORIDE', 'BENZYL DICHLORIDE', '3-CHLOROPROPENE', 'HEXACHLORO-1,3-BUTADIENE', 'N-PERFLUOROOCTANE', 'CHLOROMETHANE', '1,2,3,4-TETRAFLUOROBENZENE', '2-BROMOBUTANE', 'HEXACHLOROBENZENE', '1-IODOPROPANE', 'TRICHLOROETHYLENE', '2,3,4,5,6-PENTAFLUOROTOLUENE', '1,2-DIFLUOROTETRACHLOROETHANE', '3-BROMO-1-PROPENE', 'PERFLUORO-2,3-DIMETHYLBUTANE', '1,2-DIBROMOCHLOROTRIFLUOROETHANE', 'HEXACHLOROETHANE', 'M-DIFLUOROBENZENE', '1,2,4-TRICHLOROBENZENE', 'PHOSGENE', 'M-CHLORONITROBENZENE', 'HEXAFLUOROBENZENE', '1-BROMOOCTANE', 'MONOCHLOROACETIC ACID', '1,1,2-TRICHLOROTRIFLUOROETHANE', '1,1-DIFLUOROETHANE', 'CARBON DISULFIDE', '2-METHYLTHIOPHENE', 'CYCLOPENTANETHIOL', '2-PROPANETHIOL', '1-PENTANETHIOL', '2-METHYL-1-PROPANETHIOL', 'DI-ISO-PROPYL SULFIDE', '2-METHYL-2-BUTANETHIOL', '1-BUTANETHIOL', 'METHYL N-BUTYL SULFIDE', 'METHYL TERT-BUTYL SULFIDE', '1-PROPANETHIOL', 'DIMETHYL SULFIDE', '1-HEPTANETHIOL', 'ISOPROPYL METHYL SULFIDE', 'TERT-OCTYL MERCAPTAN', 'METHYL N-PROPYL SULFIDE', '3,4-DIMETHYLTHIOPHENE', 'DIMETHYL SULFOXIDE', 'DIETHYL SULFATE', 'SULFOLANE', 'DI-N-PROPYL SULFONE', 'CYCLOHEXANETHIOL', 'ETHYL N-PROPYL SULFIDE', 'THIOPHENOL', 'DIETHYL SULFIDE', '3-METHYL SULFOLANE', 'THIACYCLOHEXANE', 'DI-N-BUTYL SULFIDE', 'DIETHYL DISULFIDE', 'THIACYCLOPROPANE', 'DI-ISO-BUTYL SULFIDE', 'METHYL ETHYL SULFIDE', 'THIOACETICACID', 'DI-N-PENTYL SULFIDE', 'DI-N-PROPYL SULFIDE', '3-METHYLTHIACYCLOPENTANE', '2,5-DIMETHYLTHIOPHENE', 'DIMETHYL DISULFIDE', 'NITROSYL CHLORIDE', 'HYDROGEN FLUORIDE', 'OZONE', 'HYDROGEN BROMIDE', 'SULFURIC ACID', 'DEUTERIUM OXIDE', 'HYDROGEN IODIDE', 'CARBON MONOXIDE', 'NITROGEN DIOXIDE', 'NITRIC OXIDE', 'HELIUM-4', 'SULFUR DIOXIDE', 'HYDROGEN CYANIDE', 'HYDROGEN PEROXIDE', 'AMMONIA', 'NITROUS OXIDE', 'OXYGEN', 'HYDROGEN CHLORIDE', 'CARBON DIOXIDE', 'AMMONIUM CHLORIDE']

In [19]:
df_train = df[df["Name"].isin(train_comps)].reset_index()
df_valid = df[df["Name"].isin(valid_comps)].reset_index()
df_test = df[df["Name"].isin(test_comps)].reset_index()

In [20]:
df_train.head()

,index,Name,CAS-RN,Formula,SMILES,T,Pvap,KDB_ID,Class,Subclass,Mol,Fingerprint,ln_P
0,90,N-BUTANE,106-97-8,C4H10,CCCC,134.860000,0.000669,4,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB82...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",-7.309849
1,91,N-BUTANE,106-97-8,C4H10,CCCC,144.871035,0.003877,4,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB82...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",-5.552663
2,92,N-BUTANE,106-97-8,C4H10,CCCC,154.882069,0.017450,4,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB82...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",-4.048429
3,93,N-BUTANE,106-97-8,C4H10,CCCC,164.893103,0.064001,4,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB82...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",-2.748860
4,94,N-BUTANE,106-97-8,C4H10,CCCC,174.904138,0.198505,4,Paraffinic Hydrocarbons,n-Alkanes,<rdkit.Chem.rdchem.Mol object at 0x000001BAB82...,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",-1.616940

In [21]:
print(df_train.shape)
print(df_valid.shape)
print(df_test.shape)

(26310, 13)
(6810, 13)
(8610, 13)

In [22]:
df_train.columns.tolist()

['index',
 'Name',
 'CAS-RN',
 'Formula',
 'SMILES',
 'T',
 'Pvap',
 'KDB_ID',
 'Class',
 'Subclass',
 'Mol',
 'Fingerprint',
 'ln_P']

In [23]:
# Standardized the temp. values
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df_train['T'].to_numpy().reshape(-1,1))

df_train['T_scaled'] = scaler.transform(df_train['T'].to_numpy().reshape(-1,1))
df_valid['T_scaled'] = scaler.transform(df_valid['T'].to_numpy().reshape(-1,1))
df_test['T_scaled'] = scaler.transform(df_test['T'].to_numpy().reshape(-1,1))

In [24]:
df["Fingerprint"].tolist()

[array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),
 array([1, 1, 0, ..., 0, 0, 0], shape=(2048,), dtype=uint8),

In [25]:
def getX_y(A,):
    X = np.vstack(A["Fingerprint"].tolist())
    T = A["T_scaled"].to_numpy().reshape(-1,1)
    X = np.hstack((X, T))
    y = A['ln_P'].to_numpy().reshape(-1,1)
    return X, y

In [26]:
X_valid, y_valid = getX_y(df_valid)
X_test,  y_test  = getX_y(df_test)
X_train, y_train = getX_y(df_train)

In [27]:
X_train.shape, y_train.shape

((26310, 2049), (26310, 1))

In [28]:
X_test.shape, X_valid.shape, y_test.shape, y_valid.shape

((8610, 2049), (6810, 2049), (8610, 1), (6810, 1))

In [36]:
# Let's start building the DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_percentage_error as MAPE
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score as R2

model_Tree = DecisionTreeRegressor(random_state=42)
model_Tree.fit(X_train, y_train.ravel())
y_train_Tree = model_Tree.predict(X_train)
print("For training data: ")
print("Train MAE:", MAE(y_train, y_train_Tree))
print("MAPE: ", MAPE(y_train, y_train_Tree))
print("MAE: ", MAE(y_train, y_train_Tree))
print("R2: ", R2(y_train, y_train_Tree))
print("RMSE: ", root_mean_squared_error(y_train, y_train_Tree))
y_valid_Tree = model_Tree.predict(X_valid)
print("For validation data: ")
print("MAPE: ", MAPE(y_valid, y_valid_Tree))
print("MAE: ", MAE(y_valid, y_valid_Tree))
print("R2: ", R2(y_valid, y_valid_Tree))
print("RMSE: ", root_mean_squared_error(y_valid, y_valid_Tree))

For training data:
Train MAE: 0.001971611908194476
MAPE:  0.001742076828771046
MAE:  0.001971611908194476
R2:  0.9997264430769087
RMSE:  0.07060296178486072
For validation data:
MAPE:  1.7741155063597316
MAE:  1.7445972673990235
R2:  0.5532660763556234
RMSE:  2.74224839656232

In [38]:
# Make a function for calling the model and fitting it 
import time
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error as MAE
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score as R2

def fit_predict(model, X_train, y_train, X_valid):
    start = time.time()
    model.fit(X_train, y_train.ravel())
    fit_time = time.time() - start
    return model, model.predict(X_train), model.predict(X_valid), fit_time

def model_metrics(name, y_train, y_train_pred, y_valid, y_valid_pred, fit_time=None):
    y_train, y_train_pred = np.ravel(y_train), np.ravel(y_train_pred)
    y_valid, y_valid_pred = np.ravel(y_valid), np.ravel(y_valid_pred)
    return {
        "model": name,
        "train_MAE": MAE(y_train, y_train_pred),
        "train_RMSE": root_mean_squared_error(y_train, y_train_pred),
        "train_R2": R2(y_train, y_train_pred),
        "valid_MAE": MAE(y_valid, y_valid_pred),
        "valid_RMSE": root_mean_squared_error(y_valid, y_valid_pred),
        "valid_R2": R2(y_valid, y_valid_pred),
        "fit_time_s": fit_time,
    }

In [39]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor

models_to_try = {
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(random_state=42, n_jobs=-1),
    "XGBoost": XGBRegressor(random_state=42, n_jobs=-1),
}

results = []
for name, mdl in models_to_try.items():
    fitted, p_tr, p_va, t = fit_predict(mdl, X_train, y_train, X_valid)
    results.append(model_metrics(name, y_train, p_tr, y_valid, p_va, t))

pd.DataFrame(results)

,model,train_MAE,train_RMSE,train_R2,valid_MAE,valid_RMSE,valid_R2,fit_time_s
0,Decision Tree,0.001972,0.070603,0.999726,1.744597,2.742248,0.553266,40.740460
1,Random Forest,0.314885,0.582203,0.981398,1.437179,2.254949,0.697929,252.344966
2,XGBoost,0.783024,1.339202,0.901578,1.323195,2.110358,0.735426,5.543770